set(_usb_blaster_srcs usb_blaster.c)
if(OPENOCD_ENABLE_USB_BLASTER)
    list(APPEND _usb_blaster_srcs ublast_access_ftdi.c)
endif()
if(OPENOCD_ENABLE_USB_BLASTER_2)
    list(APPEND _usb_blaster_srcs ublast2_access_libusb.c)
endif()

openocd_add_object_library(jtag_drivers_usb_blaster ${_usb_blaster_srcs})
target_include_directories(jtag_drivers_usb_blaster PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/..")
if(OPENOCD_HAVE_LIBUSB1)
    target_link_libraries(jtag_drivers_usb_blaster PUBLIC OpenOCD::libusb1)
endif()
if(OPENOCD_HAVE_LIBFTDI)
    target_link_libraries(jtag_drivers_usb_blaster PUBLIC OpenOCD::libftdi)
endif()
