set(_driver_srcs driver.c)

if(OPENOCD_HAVE_LIBUSB1)
    list(APPEND _driver_srcs libusb_helper.c)
endif()

if(OPENOCD_ENABLE_JLINK)
    list(APPEND _driver_srcs jlink.c)
endif()
if(OPENOCD_BUILD_BITBANG)
    list(APPEND _driver_srcs bitbang.c)
endif()
if(OPENOCD_ENABLE_PARPORT)
    list(APPEND _driver_srcs parport.c)
endif()
if(OPENOCD_ENABLE_DUMMY)
    list(APPEND _driver_srcs dummy.c)
endif()
if(OPENOCD_ENABLE_FTDI)
    list(APPEND _driver_srcs ftdi.c mpsse.c)
endif()
if(OPENOCD_ENABLE_LINUXGPIOD)
    list(APPEND _driver_srcs linuxgpiod.c)
endif()
if(OPENOCD_ENABLE_JTAG_VPI)
    list(APPEND _driver_srcs jtag_vpi.c)
endif()
if(OPENOCD_ENABLE_VDEBUG)
    list(APPEND _driver_srcs vdebug.c)
endif()
if(OPENOCD_ENABLE_JTAG_DPI)
    list(APPEND _driver_srcs jtag_dpi.c)
endif()
if(OPENOCD_ENABLE_FT232R)
    list(APPEND _driver_srcs ft232r.c)
endif()
if(OPENOCD_ENABLE_AMTJTAGACCEL)
    list(APPEND _driver_srcs amt_jtagaccel.c)
endif()
if(OPENOCD_ENABLE_EP93XX)
    list(APPEND _driver_srcs ep93xx.c)
endif()
if(OPENOCD_ENABLE_AT91RM9200)
    list(APPEND _driver_srcs at91rm9200.c)
endif()
if(OPENOCD_ENABLE_GW16012)
    list(APPEND _driver_srcs gw16012.c)
endif()
if(OPENOCD_BUILD_BITQ)
    list(APPEND _driver_srcs bitq.c)
endif()
if(OPENOCD_ENABLE_PRESTO)
    list(APPEND _driver_srcs presto.c)
endif()
if(OPENOCD_ENABLE_ESP_USB_JTAG)
    list(APPEND _driver_srcs esp_usb_jtag.c)
endif()
if(OPENOCD_ENABLE_USBPROG)
    list(APPEND _driver_srcs usbprog.c)
endif()
if(OPENOCD_ENABLE_RLINK)
    list(APPEND _driver_srcs rlink.c rlink_speed_table.c)
endif()
if(OPENOCD_ENABLE_ULINK)
    list(APPEND _driver_srcs ulink.c)
endif()
if(OPENOCD_ENABLE_ANGIE)
    list(APPEND _driver_srcs angie.c)
endif()
if(OPENOCD_ENABLE_VSLLINK)
    list(APPEND _driver_srcs
        versaloon/usbtoxxx/usbtogpio.c
        versaloon/usbtoxxx/usbtojtagraw.c
        versaloon/usbtoxxx/usbtoswd.c
        versaloon/usbtoxxx/usbtopwr.c
        versaloon/usbtoxxx/usbtoxxx.c
        versaloon/versaloon.c
        vsllink.c
    )
endif()
if(OPENOCD_ENABLE_ARMJTAGEW)
    list(APPEND _driver_srcs arm-jtag-ew.c)
endif()
if(OPENOCD_ENABLE_BUSPIRATE)
    list(APPEND _driver_srcs buspirate.c)
endif()
if(OPENOCD_ENABLE_REMOTE_BITBANG)
    list(APPEND _driver_srcs remote_bitbang.c)
endif()
if(OPENOCD_ENABLE_HLADAPTER_STLINK)
    list(APPEND _driver_srcs stlink_usb.c)
endif()
if(OPENOCD_ENABLE_HLADAPTER_ICDI)
    list(APPEND _driver_srcs ti_icdi_usb.c)
endif()
if(OPENOCD_ENABLE_HLADAPTER_NULINK)
    list(APPEND _driver_srcs nulink_usb.c)
endif()
if(OPENOCD_ENABLE_RSHIM)
    list(APPEND _driver_srcs rshim.c)
endif()
if(OPENOCD_ENABLE_DMEM)
    list(APPEND _driver_srcs dmem.c)
endif()
if(OPENOCD_ENABLE_OSBDM)
    list(APPEND _driver_srcs osbdm.c)
endif()
if(OPENOCD_ENABLE_OPENDOUS)
    list(APPEND _driver_srcs opendous.c)
endif()
if(OPENOCD_ENABLE_SYSFSGPIO)
    list(APPEND _driver_srcs sysfsgpio.c)
endif()
if(OPENOCD_ENABLE_XLNX_PCIE_XVC)
    list(APPEND _driver_srcs xlnx-pcie-xvc.c)
endif()
if(OPENOCD_ENABLE_BCM2835GPIO)
    list(APPEND _driver_srcs bcm2835gpio.c)
endif()
if(OPENOCD_ENABLE_OPENJTAG)
    list(APPEND _driver_srcs openjtag.c)
endif()
if(OPENOCD_ENABLE_CMSIS_DAP_HID)
    list(APPEND _driver_srcs cmsis_dap_usb_hid.c cmsis_dap.c)
endif()
if(OPENOCD_ENABLE_CMSIS_DAP_USB)
    list(APPEND _driver_srcs cmsis_dap_usb_bulk.c)
    if(NOT OPENOCD_ENABLE_CMSIS_DAP_HID)
        list(APPEND _driver_srcs cmsis_dap.c)
    endif()
endif()
if(OPENOCD_ENABLE_IMX_GPIO)
    list(APPEND _driver_srcs imx_gpio.c)
endif()
if(OPENOCD_ENABLE_KITPROG)
    list(APPEND _driver_srcs kitprog.c)
endif()
if(OPENOCD_ENABLE_XDS110)
    list(APPEND _driver_srcs xds110.c)
endif()
if(OPENOCD_ENABLE_AM335XGPIO)
    list(APPEND _driver_srcs am335xgpio.c)
endif()

openocd_add_object_library(jtag_drivers ${_driver_srcs})

if(OPENOCD_HAVE_LIBUSB1)
    target_link_libraries(jtag_drivers PUBLIC OpenOCD::libusb1)
endif()
if(OPENOCD_HAVE_LIBFTDI)
    target_link_libraries(jtag_drivers PUBLIC OpenOCD::libftdi)
endif()
if(OPENOCD_HAVE_LIBGPIOD)
    target_link_libraries(jtag_drivers PUBLIC OpenOCD::libgpiod)
endif()
if(OPENOCD_HAVE_HIDAPI)
    target_link_libraries(jtag_drivers PUBLIC OpenOCD::hidapi)
endif()
if(OPENOCD_ENABLE_ULINK OR OPENOCD_ENABLE_ANGIE)
    target_link_libraries(jtag_drivers PUBLIC m)
endif()
if(OPENOCD_ENABLE_JLINK)
    if(OPENOCD_INTERNAL_LIBJAYLINK)
        target_link_libraries(jtag_drivers PUBLIC jaylink)
    else()
        target_link_libraries(jtag_drivers PUBLIC OpenOCD::libjaylink_system)
    endif()
endif()

if(OPENOCD_BUILD_USB_BLASTER_DRIVER)
    add_subdirectory(usb_blaster)
    target_link_libraries(jtag_drivers PUBLIC jtag_drivers_usb_blaster)
endif()

target_link_libraries(jtag_drivers PUBLIC jim)
