# Script-mode file: concatenates INPUTS and emits a comma-separated
# `0xNN,` C array initializer, replacing src/helper/bin2char.sh's
# `od -v -A n -t x1 | sed 's/ *\(..\) */0x\1,/g;/^$/d'` pipeline.
#
# Usage: cmake "-DINPUTS=<path1>;<path2>;..." -DOUTPUT=<path> -P BinToChar.cmake
#
# Implementation note: od groups 16 bytes per output line and the sed just
# rewrites each line's tokens in place, so the result has a newline every
# 16 source bytes (including a trailing newline after a final partial
# line). A per-byte CMake loop over a few hundred KB of firmware/Tcl source
# would be far too slow (hundreds of thousands of script-interpreted
# iterations); this reads each file as one hex string
# (file(READ ... HEX), CMake's native binary-to-hex primitive) and does the
# "NN" -> "0xNN," step as one whole-string regex pass. The "insert a
# newline every 16 tokens" step can't be a single regex pass the same way:
# CMake's regex engine does not support {n} bounded quantifiers as a
# find-all-matches pass (confirmed empirically - `(X){1}` behaved like a
# non-matching literal, not like an unquantified group), so that step
# chunks the token string by a fixed character width in a loop instead -
# ~(input size / 16) iterations, not one per byte, so it's still fast.

cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED INPUTS)
    message(FATAL_ERROR "BinToChar.cmake: INPUTS not set")
endif()
if(NOT OUTPUT)
    message(FATAL_ERROR "BinToChar.cmake: OUTPUT not set")
endif()

set(_hex "")
foreach(_input IN LISTS INPUTS)
    file(READ "${_input}" _file_hex HEX)
    string(APPEND _hex "${_file_hex}")
endforeach()

# "4865..." -> "0x48,0x65,..." in one native regex pass.
string(REGEX REPLACE "(..)" "0x\\1," _tokens "${_hex}")

# Insert a newline after every 16th token (od's line width: 16 bytes/line),
# including after a trailing partial group of fewer than 16. NOTE: CMake's
# regex engine does not support {n} bounded quantifiers as a plain
# find-all-matches pass - confirmed empirically ({1} behaved identically to
# a non-matching literal, not to an unquantified group) - so this can't be
# a single regex pass the way the token step above is. Each token is
# exactly 5 chars ("0xNN,"), so 16 tokens = 80 chars; chunk by that fixed
# width instead. This loops ~(input size / 16) times, not once per byte, so
# it stays fast even for a few hundred KB of input.
string(LENGTH "${_tokens}" _len)
set(_wrapped "")
set(_chunk_chars 80)
set(_pos 0)
while(_pos LESS _len)
    string(SUBSTRING "${_tokens}" ${_pos} ${_chunk_chars} _chunk)
    string(APPEND _wrapped "${_chunk}\n")
    math(EXPR _pos "${_pos} + ${_chunk_chars}")
endwhile()

file(WRITE "${OUTPUT}" "/* Autogenerated by cmake/BinToChar.cmake */\n${_wrapped}")
