# Script-mode file: generates _load-static-exts.c, the extension-registration
# table Jim_InitStaticExtensions() lives in. Faithful port of jimtcl's own
# jimtcl/make-load-static-exts.tcl.
#
# Usage: cmake -DEXTS="ext1;ext2;..." -DOUTPUT=<path> -P JimMakeLoadStaticExts.cmake
#
# EXTS is a CMake list (semicolon-separated) of extension names in
# STATIC_EXTS order (static-C extensions first, then static-Tcl extensions -
# see auto.def:611-613); this script re-sorts them by the load-priority
# table below, exactly as make-load-static-exts.tcl does. Extension names
# themselves never contain semicolons, so passing them as a CMake list is
# safe (unlike the raw Tcl source lines in JimMakeCExt.cmake).

cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED EXTS)
    message(FATAL_ERROR "JimMakeLoadStaticExts.cmake: EXTS not set")
endif()
if(NOT OUTPUT)
    message(FATAL_ERROR "JimMakeLoadStaticExts.cmake: OUTPUT not set")
endif()

# make-load-static-exts.tcl:10-18 -- load-order priority table. Default
# priority for anything not listed is 1; lsort on {priority name} pairs is
# a stable sort by priority then lexicographic name.
set(_pri_stdlib 0)
set(_pri_readdir 1)
set(_pri_glob 2)
set(_pri_oo 1)
set(_pri_tree 2)
set(_pri_pack 1)
set(_pri_binary 2)

set(_pairs "")
foreach(_ext IN LISTS EXTS)
    if(DEFINED _pri_${_ext})
        set(_p ${_pri_${_ext}})
    else()
        set(_p 1)
    endif()
    # Priorities are single digits (0-2), so plain string comparison of
    # "priority:name" sorts correctly by priority first, then
    # alphabetically by name within a priority -- matching Tcl's lsort on
    # "priority name" pairs (auto.def's priority table only ever produces
    # single-digit values).
    list(APPEND _pairs "${_p}:${_ext}")
endforeach()
list(SORT _pairs COMPARE STRING)

# Exact blank-line placement matched against the reference
# openocd_fork/jimtcl/_load-static-exts.c: one blank line before the
# preamble and one between the function signature and "{"; none anywhere
# else (verified byte-for-byte, not re-derived from Tcl puts semantics).
set(_out "\n/* autogenerated - do not edit */\n")
string(APPEND _out "#include \"jim.h\"\n")
string(APPEND _out "#include \"jimautoconf.h\"\n")
string(APPEND _out "int Jim_InitStaticExtensions(Jim_Interp *interp)\n")
string(APPEND _out "\n")
string(APPEND _out "{\n")

foreach(_pair IN LISTS _pairs)
    string(REGEX REPLACE "^[0-9]+:" "" _ext "${_pair}")
    string(APPEND _out "\textern int Jim_${_ext}Init(Jim_Interp *);\n")
endforeach()
foreach(_pair IN LISTS _pairs)
    string(REGEX REPLACE "^[0-9]+:" "" _ext "${_pair}")
    string(APPEND _out "\tJim_${_ext}Init(interp);\n")
endforeach()

string(APPEND _out "\treturn JIM_OK;\n")
string(APPEND _out "}\n")

file(WRITE "${OUTPUT}" "${_out}")
