# Script-mode file: converts a Tcl source file into a C source suitable for
# loading as a static Jim extension. Faithful port of jimtcl's own
# jimtcl/make-c-ext.tcl, ported instead of invoked directly to avoid a
# build-time tclsh dependency.
#
# Usage: cmake -DSOURCE=<path/to/ext.tcl> -DOUTPUT=<path/to/_ext.c> -P JimMakeCExt.cmake
#
# NOTE: lines are deliberately never turned into a CMake *list* (no
# file(STRINGS)/foreach(IN LISTS)). CMake lists are semicolon-separated, and
# Tcl source is full of literal semicolons (statement separators); passing
# lines through a list would let CMake re-split lines at every embedded
# semicolon, corrupting anything with a `foreach ... { ... }` or multi
# statement line (confirmed empirically against jimtcl/jsonencode.tcl before
# settling on this manual-substring approach). Lines are extracted with
# string(FIND)/string(SUBSTRING) and processed as plain strings throughout.

# Script mode does not inherit the top-level project's cmake_minimum_required;
# without this, CMake defaults to ancient policy behavior where while(TRUE)
# isn't recognized as an always-true condition (CMP0012).
cmake_minimum_required(VERSION 3.20)

if(NOT SOURCE)
    message(FATAL_ERROR "JimMakeCExt.cmake: SOURCE not set")
endif()
if(NOT OUTPUT)
    message(FATAL_ERROR "JimMakeCExt.cmake: OUTPUT not set")
endif()
if(NOT SOURCE MATCHES "\\.tcl$")
    message(FATAL_ERROR "JimMakeCExt.cmake: SOURCE ${SOURCE} is not a .tcl file")
endif()

file(READ "${SOURCE}" _content)

# One accumulator STRING (never a list) holding the C string-literal blob.
set(_c_lines "")

function(_jim_append_line line_text)
    # Blank out lines that are ENTIRELY a comment (optional leading
    # whitespace then '#' to end of line) -- make-c-ext.tcl:20. Trailing
    # inline comments on a code line are left untouched, matching the
    # ^...$-anchored Tcl regsub.
    if(line_text MATCHES "^[ \t]*#.*$")
        set(line_text "")
    endif()

    # make-c-ext.tcl:22 -- Tcl's `string map` applies these three
    # replacements in one simultaneous pass; doing them sequentially here
    # gives an identical result because backslash, quote and CR are
    # disjoint characters and no replacement VALUE reintroduces a character
    # that is itself an earlier search key. Order: backslash first (so we
    # don't touch backslashes inserted by the quote step), then quote,
    # then strip literal CR.
    string(REPLACE "\\" "\\\\" line_text "${line_text}")
    string(REPLACE "\"" "\\\"" line_text "${line_text}")
    string(REPLACE "\r" "" line_text "${line_text}")

    set(_c_lines "${_c_lines}\"${line_text}\\n\"\n" PARENT_SCOPE)
endfunction()

set(_remaining "${_content}")
while(TRUE)
    string(FIND "${_remaining}" "\n" _nl_pos)
    if(_nl_pos EQUAL -1)
        break()
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_nl_pos} _line)
    _jim_append_line("${_line}")
    math(EXPR _next "${_nl_pos} + 1")
    string(SUBSTRING "${_remaining}" ${_next} -1 _remaining)
endwhile()
# Final line with no trailing newline (gets(2) still returns it once before EOF).
if(NOT _remaining STREQUAL "")
    _jim_append_line("${_remaining}")
endif()

# Strip the final join-separator newline: [join $sourcelines \n] puts a
# separator strictly BETWEEN elements, never after the last one.
string(REGEX REPLACE "\n$" "" _c_lines "${_c_lines}")

get_filename_component(_basename "${SOURCE}" NAME)
get_filename_component(_pkgname "${SOURCE}" NAME_WE)

set(_out "/* autogenerated - do not edit */\n")
string(APPEND _out "#include <jim.h>\n")
string(APPEND _out "int Jim_${_pkgname}Init(Jim_Interp *interp)\n")
string(APPEND _out "{\n")
string(APPEND _out "\tif (Jim_PackageProvide(interp, \"${_pkgname}\", \"1.0\", JIM_ERRMSG)) return JIM_ERR;\n")
string(APPEND _out "\treturn Jim_EvalSource(interp, \"${_basename}\", 1, ${_c_lines});\n")
string(APPEND _out "}\n")

file(WRITE "${OUTPUT}" "${_out}")
